import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'
import SidebarCart from '@/Cart/SidebarCart'
import { useState } from 'react'
import AccountCreateModalForm from '@/components/AccountCreateModalForm/AccountCreateModalForm'
import MobileSidebarNav from '@/components/header/mobileSidebarNav/MobileSidebarNav'
import MobileSearchDropdown from '@/components/MobileSearchDropdown/MobileSearchDropdown'
import Main from './home/Main'
import Categories from './categories/Categories'
import VendorShopPage from './vendor/VendorShopPage'
import VendorSignUpPage from './vendor/VendorSignUpPage'
import OrderTrackPage from './vendor/OrderTrackPage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // mobile searchbar dropdown state
  const [isMobileSearch, SetIsMobileSearch] = useState(false);
  // mobile sidebar nav state
  const [isMobileNavOpen, SetIsMobileNavOpen] = useState(false);
  // side cart toggle functionalities start here
  const [isCartOpen, SetIsCartOpen] = useState(false);
  const toggleSidebarCart = () => {
    SetIsCartOpen(!isCartOpen);
  };
  // side cart toggle functionalities end here


  // this functionality for open and close account create modal, start here
  const [isOpen, setIsOpen] = useState(false);

  const handleOpenModal = () => {
    setIsOpen(true);
  };

  const handleCloseModal = () => {
    setIsOpen(false);
  };

  const handleOverlayClick = (event) => {
    if (event.target === event.currentTarget) {
      handleCloseModal();
    }
  };
  // this functionality for open and close account create modal, end here

  // mobile Sidebar nav toggle functionality start here===================>
  const toggleSidebarNav = () => {
    SetIsMobileNavOpen(!isMobileNavOpen);
  };
  // mobile Sidebar nav toggle functionality end here=======================>

  // mobile searchbar dropdown toggle functionality start here
  const toggleMobileSearchDropdown = () => {
    SetIsMobileSearch(!isMobileSearch);
  };
  // mobile searchbar dropdown toggle functionality end here

  return (
    <>
      <Head>
        <title>Bazar UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header toggleMobileSearchDropdown={toggleMobileSearchDropdown} toggleSidebarNav={toggleSidebarNav} toggleSidebarCart={toggleSidebarCart} handleOpenModal={handleOpenModal} />

        {/* homepage component */}
        {/* <Main /> */}

        {/* category page */}
        {/* <Categories /> */}


        {/* vendor =================================> */}



        {/* vendor shop page====================== */}


        {/* <VendorShopPage /> */}

        {/* <OrderTrackPage /> */}

        <VendorSignUpPage />



        {/* vendor =================================!> */}


        <AccountCreateModalForm handleCloseModal={handleCloseModal} handleOpenModal={handleOpenModal} handleOverlayClick={handleOverlayClick} isOpen={isOpen} />

        {/* mobile nav component */}
        {
          isMobileNavOpen && <MobileSidebarNav
            toggleSidebarNav={toggleSidebarNav}
          />
        }

        {/* mobile search component */}
        {
          isMobileSearch && <MobileSearchDropdown
            toggleMobileSearchDropdown={toggleMobileSearchDropdown}
          />
        }


        {
          isCartOpen && <SidebarCart isCartOpen={isCartOpen} toggleSidebarCart={toggleSidebarCart} />
        }
        <Footer />
      </main>
    </>
  )
}
